### PR TITLE
Add readthedocs.yml

### PR DESCRIPTION
**Pull request by koic**
This PR adds readthedocs.yml.

It is expected that the following homepage will be pushlished by this setting.

https://rubocop-performance.readthedocs.io/

Refer https://github.com/rubocop-hq/rubocop-performance/blob/v1.0.0/rubocop-performance.gemspec#L25.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop-performance/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop-performance/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
You'll add some pages here later, right? Maybe we can also add as a domain alias `performance.rubocop.org` or something like this.

**Comment by koic** [comment]
Yes. I think documents will be added as needed later.

> Maybe we can also add as a domain alias `performance.rubocop.org` or something like this.

`performance.rubocop.org` sounds good 🌟

**Comment by koic** [comment]
I expect the following manuals to be displayed at https://rubocop-performance.readthedocs.io/.
https://github.com/rubocop-hq/rubocop-performance/tree/v1.2.0/manual

I'd like to merge this PR and try to solve #45.

**Comment by bbatsov** [comment]
👍

**Pull request merged**
